spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./project4-data-file
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-ui
server:
  port: 8081
  servlet:
    session:
      timeout: 10s