version: '3.3'

services:
  tomcat:
    build:
      context: .
      dockerfile: Tomcat.Dockerfile
    image: udacity-tomcat
    container_name: udacity-tomcat
    ports:
      - 8080:8080
    networks:
      - cluster
    volumes:
      - tomcat-data:/usr/local/tomcat/webapps:Z

  splunk:
    environment:
      - "SPLUNK_START_ARGS=--accept-license --no-prompt --answer-yes"
      - "SPLUNK_USERNAME=admin"
      - "SPLUNK_PASSWORD=admin123456"
    hostname: splunk
    image: splunk/splunk:latest
    container_name: udacity-splunk
    ports:
      - 8000:8000
      - 8088:8088
      - 9997:9997
    restart: always
    networks:
      - cluster

  jenkins:
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    image: udacity-jenkins
    container_name: udacity-jenkins
    restart: on-failure
    environment:
      JENKINS_USER: jenkins_user
      JENKINS_PASSWORD: jenkins_pass
      TOMCAT_USER: tomcat_user
      TOMCAT_PASSWORD: tomcat_pass
    volumes:
      - jenkins_data:/var/jenkins_home
    ports:
      - 9000:8080
    networks:
      - cluster

networks:
  cluster:
    driver: bridge
volumes:
  tomcat-data:
  jenkins_data: