jenkins:
  securityRealm:
    local:
      allowsSignup: true
      users:
        - id: ${JENKINS_USER}
          password: ${JENKINS_PASSWORD}
  # authorizationStrategy:
  #   globalMatrix:
  #     permissions:
  #       - "Overall/Administer:ecommerce"
  #       - "Overall/Read:anonymous"
  #       - "Job/Read:anonymous"
  #       - "View/Read:anonymous"
  authorizationStrategy:
    loggedInUsersCanDoAnything: true
  security:
    globalJobDslRead: true
    agentBuild: true
    scmTag: true

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "tomcat"
              username: ${TOMCAT_USER}
              password: ${TOMCAT_PASSWORD}
              description: "Tomcat credentials for deployment."
              scope: GLOBAL
unclassified:
  location:
    url: http://127.0.0.1:8080

jobs:
  - script: >
      pipelineJob('e-Commerce') {
          description("Udacity Nanodegree e-Commerce Application")
          properties{
              githubProjectUrl ('https://github.com/viettran4718/viettq_udacity_java_nd035-c4-Security-and-DevOps.git')
          }
          triggers {
              githubPush()
          }
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url('https://github.com/viettran4718/viettq_udacity_java_nd035-c4-Security-and-DevOps.git')
                          }
                          branch('master')
                      }
                  }
                  scriptPath('starter_code/Jenkinsfile')
              }
          }
      }